scikit-hep/awkward-array

- awkward/array/union.py
Although #8 was about `test_union_ufunc`, the bug was in `fromtags` (used to set up the arrays in that test).
> fix fromtags order of operations, closing #8

- awkward/array/chunked.py
- awkward/array/indexed.py
- awkward/array/jagged.py
- awkward/array/masked.py
- awkward/array/objects.py
- awkward/array/table.py
- awkward/array/union.py
- awkward/array/virtual.py
- awkward/version.py
The `out` parameter in Numpy ufuncs are for in-place operations. awkward-array does not support in-place operations, so we detect this and forbid it.
> Forbid in place operations

- awkward/persist.py
Possible fix for and closes #67.
> Allow older awkwardarrys to be read in from hdf5

- awkward/array/jagged.py
This saves two expensive numpy.take() operations and also adds some badly-needed documentation.
PR with respect to #70 
While working on this, I actually found that another ordering of distinct pairs gives much simpler code (although about the same performance): `[[0,1], [0,2], [1,2], [0,3], [1,3], [2,3], ...]`
The same treatment can also be done for pairs.  One might make the argument that this is preferred in that it puts pairs of the 'best' options first, which would enable a simple slice for disambiugation schemes such as "highest sum pT"
Some profiling studies show that this is about 10x faster than the previous implementation, and about 10x slower (only!) than a numba implementation, although a fair portion of the time is spent in the infamous  `offsets2parents` call.  For extra fun …
> Implement direct argdistincts calculation

- awkward-numba/awkward/numba/array/jagged.py
@jpivarski this just adds two common signatures to the njit, I don't think this is too onerous on import (I don't notice it).
> Add float32 signatures to numba njits

- awkward/array/base.py
- awkward/array/chunked.py
- awkward/array/indexed.py
- awkward/array/jagged.py
- awkward/array/masked.py
- awkward/array/objects.py
- awkward/array/table.py
- awkward/array/union.py
- awkward/array/virtual.py
- awkward/version.py
- tests/test_methods.py
@lgray This is the global switch to turn off all property checks (probably minor) and validity checks (likely a significant performance cost).
```python
import awkward.array.base
awkward.array.base.AwkwardArray.check_prop_valid = False
awkward.array.base.AwkwardArray.check_whole_valid = False
```
It was also one of the features [promised in the specification](https://github.com/scikit-hep/awkward-array/blob/master/specification.adoc#global-switches-and-types) but not implemented until now.
> implement AwkwardArray.check_prop_valid and AwkwardArray.check_whole_valid

- .travis.yml
- appveyor.yml
- awkward/__init__.py
- awkward/array/jagged.py
- awkward/array/objects.py
- awkward/array/union.py
- awkward/arrow.py
- awkward/persist.py
- awkward/type.py
- awkward/version.py
- tests/test_arrow.py
Arrow → Awkward has existed for a while; Awkward → Arrow will probably be needed in the near future. (It keeps coming up; if it's as easy as I say it is, this PR will be quick.)
> Convert awkward arrays to Arrow

- awkward/array/jagged.py
- awkward/array/table.py
- awkward/arrow.py
- awkward/version.py
Making sure that `JaggedArray._broadcast`, `Table.__setitem__` are robust against different types, etc.
> Clean up any issues of losing table keys after masking or indexing

- awkward/arrow.py
- awkward/persist.py
- awkward/version.py
- tests/test_arrow.py
save and toparquet should have the same order of arguments: filename, then array to save (and awkward.save's order is set to be consistent with numpy.save)
> Consistency in awkward.save, awkward.toparquet argument order

- LICENSE
- tests/test_physics.py
Hi, I have to change something about the unit test for concatenation to reveal an issue.
Unfortunately, the concatenation didn't work after all for TLorentzVectorArrays and the like. It took me some time to understand what happened. When the vector array is created with `from_ptetaphim`, [this mixin here](https://github.com/scikit-hep/uproot-methods/blob/master/uproot_methods/base.py#L90) dynamically creates a new class. Since the class is different for every call of `from_ptetaphim`, [this check](https://github.com/scikit-hep/awkward-array/blob/master/awkward/array/base.py#L409) will fail even if the classes are for all intents and purposes the same.
My unit test concatenated arrays which themselves, which is the only case where the classes are actually the same and it will work :) I …
> More general unit test for Lorentz vector array concatenation

- awkward/util.py
- awkward/version.py
This is the  code transfer which was discussed in https://github.com/scikit-hep/uproot-methods/pull/48, adding the following util functions:
* `_normalize_arrays`
* `unwrap_jagged`
* `wrapjaggedmethod`
Final names to be discussed. `_normalize_arrays` with underscore since not used outside of `wrapjaggedmethod`.
> Receive wrapjagged functionality from uproot-methods

- awkward/array/jagged.py
Hi, while trying to fix a bug I have in my analysis, I noticed this double-implementation of `compact` and `iscompact` in `jagged.py`. the exact same 27 lines are repeated 2 times, I thought it might be good to fix that.
Cheers!
> Remove duplicate compact and iscompact in jagged

- awkward/array/masked.py
- awkward/arrow.py
- awkward/version.py
- tests/test_arrow.py
If an Arrow ListArray (from RecordBatches at least) has at least 7 elements, its offset `buffers` will include a trailing `0`. We can detect this (other than non-monotonicity) because we have a "length" parameter from the RecordBatch that tells us where to cut off the excess data.
However, this means that the length must be propagated through my `popbuffers` function, since the correct length at one level of nested jaggedness can be completely unrelated to the next level: I have to discover the next length in from `offsets[-1]` (which is only correct if `offsets` has the right length). It can be computed recursively—but that had to be added.
Moreover, it means that I must deal with the current level of jaggedness before descending into the next one, because the only way to give it the …
> Issue arrowbuffers toobig

- awkward/array/jagged.py
- tests/test_crosscut.py
I noticed this from a large array loaded through uproot. If `content` goes past the last offset in a JaggedArray, the last range run over by `ufunc.reduceat()` will be from that offset to the end of `content`, regardless of whether those elements are actually in the array.
Example:
```python
import awkward
a = awkward.JaggedArray.fromcounts([1, 2, 3], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print('a =', a)
print('a.count() =', a.count())
```
Output:
```python
a = [[1] [2 3] [4 5 6]]
a.count() = [1 2 7]
```
The elements past 6 are being counted as part of the last row. The change that I made was to take all offsets less then `len(content)`, so that if this value is not equal to the last offset, the last row will still be counted correctly.
Incidentally, there is apparently a test that already …
> Fix JaggedArray._reduce() when content goes past last offset

- awkward/array/base.py
- tests/test_jagged.py
- tests/test_table.py
I've added a few methods that help make `zip()` a reversible process. This addresses #115, although the main reason I've been interested in this is to get a tuple of arrays out of `JaggedArray.argcross()` as opposed to an array of tuples, as referenced in the issue.
> Add unzip functionality for tables and arrays

- awkward/array/jagged.py
An array can be compact even if `self.offsetsaliased` is `False` (because `tmp._starts.base` and `tmp._stops.base` are `None`).
> [array] tojagged: fixed compactness condition

- awkward/array/jagged.py
- tests/test_jagged.py
This fixes another issue that I noticed with JaggedArrays that have content beyond the visible elements in the array. Take the following cases of trying to use boolean indexing/masking:
```python
>>> from awkward import JaggedArray
>>> array = JaggedArray.fromcounts([1], [0, 1])
>>> array
<JaggedArray [[0]] at 0x7f86725d72b0>
>>> indices = JaggedArray.fromcounts([1], [True])
>>> indices
<JaggedArray [[True]] at 0x7f867082c828>
>>> array[indices]
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/user/cern/iris/awkward-array/awkward/array/jagged.py", line 543, in __getitem__
return self.copy(starts=offsets[:-1].reshape(intheadsum.shape), stops=offsets[1:].reshape(intheadsum.shape), content=thyself._content[headcontent])
IndexError: boolean index did not …
```
> Boolean indexing fix

- awkward/array/chunked.py
- awkward/array/indexed.py
- awkward/array/jagged.py
- awkward/array/masked.py
- awkward/array/objects.py
- awkward/array/table.py
- awkward/array/union.py
- awkward/array/virtual.py
- awkward/persist.py
This is a proposal to move the functionality of [`persist.serialize`](https://github.com/scikit-hep/awkward-array/blob/master/awkward/persist.py#L236) into a class.  
Following is a brief overview I'd be happy to elaborate on as questions arise.
This change enables more customization of the internal behavior of `serialize`, in particular for the storing of NumPy arrays - which would require copying the entire function at the moment. Examples of such modifications are:
* storing NumPy arrays directly in an `h5py` storage as a `Dataset`
* chunking on save (injecting `ChunkedArray` of `VirutalArrays` around NumPy arrays)
* Deduplication across multiple serializations to the same storage possible.
* Deduplication of deserialized objects possible (e.g. for adding *only new* stuff to a …
> Proposal: class-ify persists.serialize

- awkward/array/jagged.py
> Return JaggedArray index with correct dtype if empty

- awkward/array/jagged.py
Prevents bugs such as:
```python
import awkward, numpy as np
offsets, = np.where([1, 0, 1, 0, 0, 1])
awkward.JaggedArray.fromoffsets(offsets, np.arange(5))
```
> Don't let JaggedArray.fromoffsets construct from a view

- awkward/array/jagged.py
- tests/test_jagged.py
`JaggedArray.__getitem__` allows for retrieving part of the array based on advanced indexing, but `__setitem__` currently does not allow assignment of array contents in the same way (which is possible for `numpy.ndarray`). I've added this functionality to `JaggedArray`. It's necessary for some of the array manipulations I've needed--specifically, to convert from an integer index array to an equivalent boolean mask.
> allow assignment within JaggedArray by boolean or integer indexing

- awkward/array/base.py
- awkward/version.py
Numpy changed its exception type for `numpy.fromiter(not-a-buffer)` from `AttributeError` (which didn't make much sense) to `TypeError` (which does). Now we check both in `AwkwardArray._util_toarray`. This should work for old and new Numpys and still distinguish between objects with a buffer protocol and sequence-like objects.
> Adapt for Numpy 1.17.0

- awkward/array/jagged.py
- awkward/version.py
Fixes JaggedArray.__getitem__ for integer indexes that have a too-small integer type; this MIGHT be the problem in #172.
> Fix issue #172

- awkward/array/chunked.py
- tests/test_chunked.py
This addresses the following odd behavior:
```python
>>> import awkward
>>> a = awkward.ChunkedArray([[[0, 1]]])
>>> a
<ChunkedArray [[0 1]] at 0x7fb301038320>
>>> len(a)
1
>>> b = a.flatten()
>>> b
<ChunkedArray [0 1] at 0x7fb301038358>
>>> len(b)
1
```
`len` is determined from `offsets[-1]`, but `offsets` doesn't get updated after `flatten()`.
> Fix len of ChunkedArray after chunksizes changes

- awkward/array/base.py
- awkward/version.py
We had been using `__getstate__` and `__setstate__`, but these assume that a class can be referenced by a qualname for reconstruction (even though we never use it). The most complete (functional) way to pickle something is through `__reduce__`, which overcomes the problem of classes generated on the fly not having a qualname.
> Make sure that classes generated on the fly are pickleable.

- awkward/array/table.py
- tests/test_table.py
Currently, iterating over a Row in a Table with columns that aren't labeled '0', '1', '2', etc., will fail, making it appear as if every Row is empty:
```python
>>> import awkward
>>> t = awkward.Table({'a': [1]})
<Table [<Row 0>] at 0x7fc15bf93090>
>>> t['a']
array([1])
>>> t[0]
<Row 0>
>>> len(t[0])     
0
```
This is fixed here, so that the actual OrderedDict of column names will be iterated over.
> Fix iteration over Rows

- .travis.yml
- awkward/pandas.py
- setup.py
- tests/test_pandas.py
I'm not sure what the plan for python2 support is, but when using awkward array in python 2, the awkward.pandas module cannot be loaded, because there is a clash in the module name between pandas itself, and the awkward.pandas module.  The import that takes place internally for `pandas.api.extension` then fails:
```bash
$ python --version
Python 2.7.15
$ python -c "import awkward.pandas as mod;print(mod)"
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/home/ben/projects/awkward-array/awkward/pandas.py", line 6, in <module>
import pandas.api.extensions
ImportError: No module named api.extensions
```
This is addressed by insisting on absollute_imports, which is default in python3 and needs importing from `__future__` in python2.
> Add absolute_import needed for python2

- awkward/array/jagged.py
- tests/test_arrow.py
I'm still not sure this is the best idea.
> Create special exception in jagged fromoffsets for zero-copy arrow conversion

- awkward/arrow.py
- tests/test_arrow.py
There's now a 64-bit indexed ListArray, StringArray, and BinaryArray types in pyarrow.
I've put in a defaulted-false argument in `toarrow()` where the user can drive the index type used when serializing jagged arrays.
> Add LargeListArray, LargeBinaryArray, LargeStringArray to pyarrow serialization options.

- awkward/array/jagged.py
Just a missing instance of using `type(self)` rather than `self.JaggedArray` which should be valid here.
> Make methods stick on jagged getitem[jagged bool mask]

- awkward/array/virtual.py
Also require cache to conform to MutableMapping interface, i.e. KeyError
is the only exception that indicates trouble.
> Actually use cache for newly-constructed VirtualArrays

- awkward/array/jagged.py
- tests/test_jagged.py
`JaggedArray._concatenate_axis1` performs an unexpected dtype change, e.g. two `JaggedArray`s with `np.float32` dtype will result in one `JaggedArray` with dtype `np.float64`.
This is caused by the [built-in `sum(x)` function](https://docs.python.org/3/library/functions.html#sum) which does behave like `reduce(lambda a, b: a + b, x, int(0))` i.e. with an explicit `initializer=0` for [`reduce`](https://docs.python.org/3/library/functools.html#functools.reduce).
Using [`numpy.sum`](https://numpy.org/doc/1.18/reference/generated/numpy.sum.html) is not an option either since it has special dtype determination rules regarding integers.
I've also added a corresponding test.
> Fix unexpected dtype change in JaggedArray._concatenate_axis1
