scikit-hep/awkward-array

.vscode/settings.json
awkward/array/jagged.py
tests/test_jagged.py

This is a modification of pull request #1 to comply with coding conventions and to fix one bug.

Add combinations 2

---

.travis.yml
appveyor.yml
awkward/persist.py
awkward/version.py
setup.py
tests/test_hdf5.py

This uses PyTest (and a pytest fixture) to run a test on HDF5.

Adding test for hdf5

---

awkward/array/jagged.py
tests/test_methods.py

Also some method unit tests.  Not sure if I'm really exercising very many methods features.

Pass method mixins through JaggedArray __getitem__

---

awkward/array/jagged.py
awkward/version.py

Fix boolean jagged array reductions (`any` and `all`) when `_canuseoffset()`

---

awkward/array/jagged.py
awkward/array/table.py
awkward/array/virtual.py
awkward/arrow.py
awkward/generate.py
awkward/persist.py
awkward/type.py
awkward/util.py
awkward/version.py

Some were missed in the grand sweep for 0.8.0.

remove more dependences on global awkwardlib/numpy

---

awkward/array/jagged.py
awkward/version.py

About a factor 2 improvement in recurse when you know the arrays are the same shape.

Modifications to speed up recurse in when certain information is known

---

awkward-numba/awkward/numba/array/jagged.py

@jpivarski If there's a fourth one we should remove the explicit signatures.

Add int64 signature to numba njit

---

awkward/array/jagged.py
awkward/version.py

The first commit is for scikit-hep/uproot-methods#44.
I'll get to scikit-hep/awkward-array#100 in a moment.

fix issues related to scikit-hep/uproot-methods#44 and scikit-hep/awkward-array#100

---

awkward/array/indexed.py
awkward/array/jagged.py
tests/test_jagged.py

Guard against zero-length permutations in IndexedArray

---

awkward-numba/awkward/numba/array/base.py
awkward/array/base.py
awkward/array/chunked.py
awkward/array/jagged.py
awkward/array/masked.py
awkward/array/objects.py
awkward/array/table.py
awkward/array/union.py
awkward/array/virtual.py
tests/test_jagged.py

The little methods discussed on issue #90.
At some point, we also talked about dropping `JaggedArray.pandas`; doing that now.

Implement pad and fillna

---

awkward/array/jagged.py
tests/test_jagged.py

Allows combinations up to 5, because why not? :)
I think, though, with some careful thought one can also use `np.repeat()` to generalize

Add argchoose function to jagged array

---

awkward/array/base.py
awkward/array/jagged.py
awkward/array/table.py
awkward/version.py

Added support for awkward-array style concatenate on axis=0 for Table.

Awkward-array style concatenate for Table

---

awkward-numba/awkward/numba/array/jagged.py
awkward/version.py

Added missing return in _broadcast of JaggedArrayNumba

Added missing return

---

awkward/array/jagged.py

fix for creating TLorentzVectorArray from JaggedArray slices

---

awkward/array/base.py
awkward/array/table.py
awkward/arrow.py
awkward/generate.py
awkward/persist.py
awkward/version.py
tests/test_arrow.py

A few tweaks to support lazy arrays in uproot. awkward 0.10.0 will be the new minimally required version of uproot-methods and uproot.

Awkward lazyarrays

---

awkward/array/chunked.py
awkward/type.py
awkward/version.py

Anything that I need to fix to get the LPC HATS tutorials working goes here.

fixes for LPC HATS

---

awkward/array/jagged.py
awkward/version.py
tests/test_issues.py

Work-around Numpy's ufunc.reduceat

---

awkward-cpp/awkward/cpp/array/_jagged.cpp
awkward-cpp/awkward/cpp/array/awk_util.h
awkward-cpp/awkward/cpp/array/jagged.py
tests/test_cpp.py

Continuing to work on adding JaggedArrays methods in awkward-cpp

JaggedArrays in awk-cpp

---

awkward/array/base.py
awkward/array/jagged.py
awkward/util.py
tests/test_jagged.py

And do a few cool speedups too

Fix choose on non-offsetsaliased jagged arrays

---

awkward/array/base.py
awkward/array/chunked.py
awkward/array/indexed.py
awkward/array/jagged.py
awkward/array/masked.py
awkward/array/objects.py
awkward/array/table.py
awkward/array/union.py
awkward/array/virtual.py
awkward/version.py

Its usefulness became apparent in the CoDaS-HEP preparation.

add an axis parameter to the pad method

---

awkward/array/jagged.py
tests/test_issues.py

Stop recursing on multi-d slicing if remaining jagged array is empty

---

awkward/array/jagged.py
awkward/version.py

Fix serialization of JaggedArrays with non-simple offsets.

---

awkward/array/chunked.py
awkward/version.py

Fixes scikit-hep/uproot#412

---

awkward/array/jagged.py
awkward/array/virtual.py

Also more propagation of docstrings.
Although 0.x is dying, maybe worth running some linter on this repo anyway.

Some typos in VirtualArray
